#!/bin/bash
set -euo pipefail

PROJECT_DIR="${PROJECT_DIR:-$HOME/projects/SSO_test}"
SUBMIT_SCRIPT="${SUBMIT_SCRIPT:-$PROJECT_DIR/slurm/submit_width256_pgd_gap_threshold_tune.sh}"
RUN_ROOT_BASE="${RUN_ROOT_BASE:-$PROJECT_DIR/results/olmo_250m_width256_pgd_sigma2_10_lrscale_focused_sweep}"

# Complements submit_width256_pgd_sigma2_10_gap_fine_sweep.sh.
# Keep sigma2=10 fixed and test whether smaller PGD-only steps can make
# nonzero fallback useful without allowing the high PGD rates seen before.
SPEL_PGD_PGD_LR_SCALES="${SPEL_PGD_PGD_LR_SCALES:-0.25 0.1}"
SPEL_PGD_GAP_THRESHOLDS="${SPEL_PGD_GAP_THRESHOLDS:-1e-6 1e-5 1e-4}"

WIDTH="${WIDTH:-256}"
NUM_LAYERS="${NUM_LAYERS:-28}"
SEQ_LENGTH="${SEQ_LENGTH:-4096}"
HEAD_DIM="${HEAD_DIM:-128}"
GLOBAL_BATCH="${GLOBAL_BATCH:-128}"
MICRO_BATCH="${MICRO_BATCH:-4}"
TRAIN_TOKENS="${TRAIN_TOKENS:-250000000}"
LR="${LR:-1.5e-2}"
MIN_LR="${MIN_LR:-1.5e-3}"
LR_WARMUP_ITERS="${LR_WARMUP_ITERS:-50}"
EVAL_INTERVAL="${EVAL_INTERVAL:-100}"
EVAL_ITERS="${EVAL_ITERS:-5}"
LOG_INTERVAL="${LOG_INTERVAL:-10}"
CPUS_PER_TASK="${CPUS_PER_TASK:-8}"

SPEL_PGD_BRANCH_MODE="${SPEL_PGD_BRANCH_MODE:-auto}"
SPEL_PGD_PROJECTION_MODE="${SPEL_PGD_PROJECTION_MODE:-shared_topk}"
SPEL_PGD_PROJECTION_RANK="${SPEL_PGD_PROJECTION_RANK:-8}"
SPEL_PGD_SIGMA2_POWER_ITERATION_STEPS="${SPEL_PGD_SIGMA2_POWER_ITERATION_STEPS:-10}"
SPEL_PGD_DIRECTION_NORMALIZATION="${SPEL_PGD_DIRECTION_NORMALIZATION:-spectral}"
SPEL_PGD_TANGENT_PROJECT_AFTER_MSIGN="${SPEL_PGD_TANGENT_PROJECT_AFTER_MSIGN:-0}"

tag_value() {
  local value=$1
  value=${value//./p}
  value=${value//-/m}
  value=${value//+/p}
  printf "%s" "$value"
}

echo "Submitting width=${WIDTH} plain MCSD-PGD sigma2=10 focused PGD-lr sweep"
echo "  pgd_lr_scales=${SPEL_PGD_PGD_LR_SCALES}"
echo "  gaps=${SPEL_PGD_GAP_THRESHOLDS}"
echo "  projection=${SPEL_PGD_PROJECTION_MODE}, rank=${SPEL_PGD_PROJECTION_RANK}"
echo "  train_tokens=${TRAIN_TOKENS}, lr=${LR}, run_root_base=${RUN_ROOT_BASE}"

for pgd_lr_scale in $SPEL_PGD_PGD_LR_SCALES; do
  scale_tag=$(tag_value "$pgd_lr_scale")
  RUN_ROOT="$RUN_ROOT_BASE/pgdlr_${scale_tag}" \
  WIDTH="$WIDTH" \
  NUM_LAYERS="$NUM_LAYERS" \
  SEQ_LENGTH="$SEQ_LENGTH" \
  HEAD_DIM="$HEAD_DIM" \
  GLOBAL_BATCH="$GLOBAL_BATCH" \
  MICRO_BATCH="$MICRO_BATCH" \
  TRAIN_TOKENS="$TRAIN_TOKENS" \
  LR="$LR" \
  MIN_LR="$MIN_LR" \
  LR_WARMUP_ITERS="$LR_WARMUP_ITERS" \
  EVAL_INTERVAL="$EVAL_INTERVAL" \
  EVAL_ITERS="$EVAL_ITERS" \
  LOG_INTERVAL="$LOG_INTERVAL" \
  CPUS_PER_TASK="$CPUS_PER_TASK" \
  SPEL_PGD_BRANCH_MODE="$SPEL_PGD_BRANCH_MODE" \
  SPEL_PGD_PROJECTION_MODE="$SPEL_PGD_PROJECTION_MODE" \
  SPEL_PGD_PROJECTION_RANK="$SPEL_PGD_PROJECTION_RANK" \
  SPEL_PGD_SIGMA2_POWER_ITERATION_STEPS="$SPEL_PGD_SIGMA2_POWER_ITERATION_STEPS" \
  SPEL_PGD_DIRECTION_NORMALIZATION="$SPEL_PGD_DIRECTION_NORMALIZATION" \
  SPEL_PGD_PGD_LR_SCALE="$pgd_lr_scale" \
  SPEL_PGD_TANGENT_PROJECT_AFTER_MSIGN="$SPEL_PGD_TANGENT_PROJECT_AFTER_MSIGN" \
  SPEL_PGD_GAP_THRESHOLDS="$SPEL_PGD_GAP_THRESHOLDS" \
  bash "$SUBMIT_SCRIPT"
done
