#!/bin/bash
set -euo pipefail

PROJECT_DIR="${PROJECT_DIR:-$HOME/projects/SSO_test}"
SUBMIT_SCRIPT="${SUBMIT_SCRIPT:-$PROJECT_DIR/slurm/submit_width256_pgd_gap_threshold_tune.sh}"
RUN_ROOT_BASE="${RUN_ROOT_BASE:-$PROJECT_DIR/results/olmo_250m_width256_pgd_spectral_sigma2_gap_sweep}"

SPEL_PGD_SIGMA2_STEPS="${SPEL_PGD_SIGMA2_STEPS:-3 8 10}"
SPEL_PGD_GAP_THRESHOLDS="${SPEL_PGD_GAP_THRESHOLDS:-1e-4 5e-4 1e-3 2e-3 5e-3}"

TRAIN_TOKENS="${TRAIN_TOKENS:-250000000}"
LR="${LR:-1.5e-2}"
MIN_LR="${MIN_LR:-1.5e-3}"
LR_WARMUP_ITERS="${LR_WARMUP_ITERS:-50}"
EVAL_INTERVAL="${EVAL_INTERVAL:-100}"
EVAL_ITERS="${EVAL_ITERS:-5}"
LOG_INTERVAL="${LOG_INTERVAL:-10}"
CPUS_PER_TASK="${CPUS_PER_TASK:-8}"

SPEL_PGD_DIRECTION_NORMALIZATION="${SPEL_PGD_DIRECTION_NORMALIZATION:-spectral}"
SPEL_PGD_PROJECTION_MODE="${SPEL_PGD_PROJECTION_MODE:-shared_topk}"
SPEL_PGD_PROJECTION_RANK="${SPEL_PGD_PROJECTION_RANK:-8}"
SPEL_PGD_TANGENT_PROJECT_AFTER_MSIGN="${SPEL_PGD_TANGENT_PROJECT_AFTER_MSIGN:-0}"

echo "Submitting width=256 plain MCSD-PGD spectral sigma2/gap sweep"
echo "  sigma2_steps=${SPEL_PGD_SIGMA2_STEPS}"
echo "  gaps=${SPEL_PGD_GAP_THRESHOLDS}"
echo "  normalization=${SPEL_PGD_DIRECTION_NORMALIZATION}"
echo "  projection=${SPEL_PGD_PROJECTION_MODE}, rank=${SPEL_PGD_PROJECTION_RANK}"
echo "  train_tokens=${TRAIN_TOKENS}, lr=${LR}"
echo "  run_root_base=${RUN_ROOT_BASE}"

for sigma2_steps in $SPEL_PGD_SIGMA2_STEPS; do
  RUN_ROOT="$RUN_ROOT_BASE/sigma2_${sigma2_steps}" \
  TRAIN_TOKENS="$TRAIN_TOKENS" \
  LR="$LR" \
  MIN_LR="$MIN_LR" \
  LR_WARMUP_ITERS="$LR_WARMUP_ITERS" \
  EVAL_INTERVAL="$EVAL_INTERVAL" \
  EVAL_ITERS="$EVAL_ITERS" \
  LOG_INTERVAL="$LOG_INTERVAL" \
  CPUS_PER_TASK="$CPUS_PER_TASK" \
  SPEL_PGD_DIRECTION_NORMALIZATION="$SPEL_PGD_DIRECTION_NORMALIZATION" \
  SPEL_PGD_PROJECTION_MODE="$SPEL_PGD_PROJECTION_MODE" \
  SPEL_PGD_PROJECTION_RANK="$SPEL_PGD_PROJECTION_RANK" \
  SPEL_PGD_SIGMA2_POWER_ITERATION_STEPS="$sigma2_steps" \
  SPEL_PGD_GAP_THRESHOLDS="$SPEL_PGD_GAP_THRESHOLDS" \
  SPEL_PGD_TANGENT_PROJECT_AFTER_MSIGN="$SPEL_PGD_TANGENT_PROJECT_AFTER_MSIGN" \
  bash "$SUBMIT_SCRIPT"
done
