#!/bin/bash
set -euo pipefail

PROJECT_DIR="${PROJECT_DIR:-$HOME/projects/SSO_test}"
SBATCH_SCRIPT="${SBATCH_SCRIPT:-$PROJECT_DIR/slurm/spel_olmo_1b_h20.sbatch}"
RUN_ROOT="${RUN_ROOT:-$PROJECT_DIR/results/olmo_250m_width256_pgd_gap_threshold_tune}"

WIDTH="${WIDTH:-256}"
NUM_LAYERS="${NUM_LAYERS:-28}"
SEQ_LENGTH="${SEQ_LENGTH:-4096}"
HEAD_DIM="${HEAD_DIM:-128}"
GLOBAL_BATCH="${GLOBAL_BATCH:-128}"
MICRO_BATCH="${MICRO_BATCH:-4}"
TRAIN_TOKENS="${TRAIN_TOKENS:-250000000}"
LR="${LR:-1.5e-2}"
MIN_LR="${MIN_LR:-1.5e-3}"
LR_WARMUP_ITERS="${LR_WARMUP_ITERS:-50}"
EVAL_INTERVAL="${EVAL_INTERVAL:-100}"
EVAL_ITERS="${EVAL_ITERS:-5}"
LOG_INTERVAL="${LOG_INTERVAL:-10}"
CPUS_PER_TASK="${CPUS_PER_TASK:-8}"

SPEL_PGD_BRANCH_MODE="${SPEL_PGD_BRANCH_MODE:-auto}"
SPEL_PGD_PROJECTION_MODE="${SPEL_PGD_PROJECTION_MODE:-shared_topk}"
SPEL_PGD_PROJECTION_RANK="${SPEL_PGD_PROJECTION_RANK:-8}"
SPEL_PGD_SIGMA2_POWER_ITERATION_STEPS="${SPEL_PGD_SIGMA2_POWER_ITERATION_STEPS:-5}"
SPEL_PGD_GAP_ESTIMATOR_MODE="${SPEL_PGD_GAP_ESTIMATOR_MODE:-deflated_power}"
SPEL_PGD_MAIN_POWER_DTYPE="${SPEL_PGD_MAIN_POWER_DTYPE:-bf16}"
SPEL_PGD_DIRECTION_NORMALIZATION="${SPEL_PGD_DIRECTION_NORMALIZATION:-spectral}"
SPEL_PGD_PGD_LR_SCALE="${SPEL_PGD_PGD_LR_SCALE:-0.5}"
SPEL_PGD_TANGENT_PROJECT_AFTER_MSIGN="${SPEL_PGD_TANGENT_PROJECT_AFTER_MSIGN:-0}"
SPEL_PGD_WARM_START_UV="${SPEL_PGD_WARM_START_UV:-0}"
SPEL_PGD_GAP_THRESHOLDS="${SPEL_PGD_GAP_THRESHOLDS:-1e-4 5e-4 1e-3 2e-3}"

mkdir -p "$RUN_ROOT"

tag_value() {
  local value=$1
  value=${value//./p}
  value=${value//-/m}
  value=${value//+/p}
  printf "%s" "$value"
}

submit_gap() {
  local gap=$1
  local gap_tag
  local lr_tag
  local mode_tag
  local scale_tag
  local estimator_tag
  local main_dtype_tag
  local warm_tag
  gap_tag=$(tag_value "$gap")
  lr_tag=$(tag_value "$LR")
  mode_tag=${SPEL_PGD_PROJECTION_MODE//_/-}
  scale_tag=$(tag_value "$SPEL_PGD_PGD_LR_SCALE")
  estimator_tag=${SPEL_PGD_GAP_ESTIMATOR_MODE//_/-}
  main_dtype_tag=${SPEL_PGD_MAIN_POWER_DTYPE//_/-}
  warm_tag="cold"
  if [[ "$SPEL_PGD_WARM_START_UV" == "1" || "$SPEL_PGD_WARM_START_UV" == "true" ]]; then
    warm_tag="warm"
  fi

  local norm_tag=${SPEL_PGD_DIRECTION_NORMALIZATION//_/-}
  local job_name="plain_pgd_gap${gap_tag}_${estimator_tag}_${main_dtype_tag}_${warm_tag}_norm${norm_tag}_${mode_tag}_k${SPEL_PGD_PROJECTION_RANK}_s2${SPEL_PGD_SIGMA2_POWER_ITERATION_STEPS}_pgdlr${scale_tag}_w${WIDTH}_lr${lr_tag}"

  sbatch \
    --cpus-per-task="$CPUS_PER_TASK" \
    -J "$job_name" \
    --export=ALL,OPTIMIZER="spel_pgd_dist",WIDTH="$WIDTH",NUM_LAYERS="$NUM_LAYERS",HEAD_DIM="$HEAD_DIM",SEQ_LENGTH="$SEQ_LENGTH",GLOBAL_BATCH="$GLOBAL_BATCH",MICRO_BATCH="$MICRO_BATCH",TRAIN_TOKENS="$TRAIN_TOKENS",LR="$LR",MIN_LR="$MIN_LR",LR_WARMUP_ITERS="$LR_WARMUP_ITERS",EVAL_INTERVAL="$EVAL_INTERVAL",EVAL_ITERS="$EVAL_ITERS",LOG_INTERVAL="$LOG_INTERVAL",RUN_ROOT="$RUN_ROOT",JOB_NAME="$job_name",SAVE_CHECKPOINT=0,SPEL_PGD_BRANCH_MODE="$SPEL_PGD_BRANCH_MODE",SPEL_PGD_PROJECTION_MODE="$SPEL_PGD_PROJECTION_MODE",SPEL_PGD_PROJECTION_RANK="$SPEL_PGD_PROJECTION_RANK",SPEL_PGD_GAP_THRESHOLD_REL="$gap",SPEL_PGD_SIGMA2_POWER_ITERATION_STEPS="$SPEL_PGD_SIGMA2_POWER_ITERATION_STEPS",SPEL_PGD_GAP_ESTIMATOR_MODE="$SPEL_PGD_GAP_ESTIMATOR_MODE",SPEL_PGD_MAIN_POWER_DTYPE="$SPEL_PGD_MAIN_POWER_DTYPE",SPEL_PGD_DIRECTION_NORMALIZATION="$SPEL_PGD_DIRECTION_NORMALIZATION",SPEL_PGD_PGD_LR_SCALE="$SPEL_PGD_PGD_LR_SCALE",SPEL_PGD_TANGENT_PROJECT_AFTER_MSIGN="$SPEL_PGD_TANGENT_PROJECT_AFTER_MSIGN",SPEL_PGD_WARM_START_UV="$SPEL_PGD_WARM_START_UV" \
    "$SBATCH_SCRIPT"
}

echo "Submitting width=${WIDTH} plain SpEL-PGD gap-threshold tune"
echo "  LR=${LR}, TRAIN_TOKENS=${TRAIN_TOKENS}, GLOBAL_BATCH=${GLOBAL_BATCH}, MICRO_BATCH=${MICRO_BATCH}"
echo "  projection=${SPEL_PGD_PROJECTION_MODE}, rank=${SPEL_PGD_PROJECTION_RANK}, sigma2_steps=${SPEL_PGD_SIGMA2_POWER_ITERATION_STEPS}"
echo "  gap_estimator=${SPEL_PGD_GAP_ESTIMATOR_MODE}, main_power_dtype=${SPEL_PGD_MAIN_POWER_DTYPE}, warm_start_uv=${SPEL_PGD_WARM_START_UV}, normalization=${SPEL_PGD_DIRECTION_NORMALIZATION}, pgd_lr_scale=${SPEL_PGD_PGD_LR_SCALE}"
echo "  tp_after_msign=${SPEL_PGD_TANGENT_PROJECT_AFTER_MSIGN}, gaps=${SPEL_PGD_GAP_THRESHOLDS}"
echo "  RUN_ROOT=${RUN_ROOT}"

for gap in $SPEL_PGD_GAP_THRESHOLDS; do
  submit_gap "$gap"
done
