#!/bin/bash
set -euo pipefail

PROJECT_DIR="${PROJECT_DIR:-$HOME/projects/SSO_test}"
SUBMIT_SCRIPT="${SUBMIT_SCRIPT:-$PROJECT_DIR/slurm/submit_width256_pgd_gap_threshold_tune.sh}"
RUN_ROOT="${RUN_ROOT:-$PROJECT_DIR/results/olmo_250m_width256_pgd_block2_fp32_gap_control_sweep}"

# FP32 block-2 gap estimator sweep.  Keep thresholds above the ultra-tiny
# range used for BF16/deflated probes so PGD usage is controlled by a meaningful
# FP32 spectral-gap estimate.
SPEL_PGD_GAP_THRESHOLDS="${SPEL_PGD_GAP_THRESHOLDS:-0 1e-6 3e-6 1e-5 3e-5 1e-4 3e-4 1e-3}"

WIDTH="${WIDTH:-256}"
NUM_LAYERS="${NUM_LAYERS:-28}"
SEQ_LENGTH="${SEQ_LENGTH:-4096}"
HEAD_DIM="${HEAD_DIM:-128}"
GLOBAL_BATCH="${GLOBAL_BATCH:-128}"
MICRO_BATCH="${MICRO_BATCH:-4}"
TRAIN_TOKENS="${TRAIN_TOKENS:-250000000}"
LR="${LR:-1.5e-2}"
MIN_LR="${MIN_LR:-1.5e-3}"
LR_WARMUP_ITERS="${LR_WARMUP_ITERS:-50}"
EVAL_INTERVAL="${EVAL_INTERVAL:-100}"
EVAL_ITERS="${EVAL_ITERS:-5}"
LOG_INTERVAL="${LOG_INTERVAL:-10}"
CPUS_PER_TASK="${CPUS_PER_TASK:-8}"

SPEL_PGD_BRANCH_MODE="${SPEL_PGD_BRANCH_MODE:-auto}"
SPEL_PGD_PROJECTION_MODE="${SPEL_PGD_PROJECTION_MODE:-shared_topk}"
SPEL_PGD_PROJECTION_RANK="${SPEL_PGD_PROJECTION_RANK:-8}"
SPEL_PGD_SIGMA2_POWER_ITERATION_STEPS="${SPEL_PGD_SIGMA2_POWER_ITERATION_STEPS:-10}"
SPEL_PGD_GAP_ESTIMATOR_MODE="${SPEL_PGD_GAP_ESTIMATOR_MODE:-block2_fp32}"
SPEL_PGD_DIRECTION_NORMALIZATION="${SPEL_PGD_DIRECTION_NORMALIZATION:-spectral}"
SPEL_PGD_PGD_LR_SCALE="${SPEL_PGD_PGD_LR_SCALE:-0.5}"
SPEL_PGD_TANGENT_PROJECT_AFTER_MSIGN="${SPEL_PGD_TANGENT_PROJECT_AFTER_MSIGN:-0}"

echo "Submitting width=${WIDTH} plain MCSD-PGD block2-fp32 gap-control sweep"
echo "  gaps=${SPEL_PGD_GAP_THRESHOLDS}"
echo "  gap_estimator=${SPEL_PGD_GAP_ESTIMATOR_MODE}, sigma2_steps=${SPEL_PGD_SIGMA2_POWER_ITERATION_STEPS}"
echo "  projection=${SPEL_PGD_PROJECTION_MODE}, rank=${SPEL_PGD_PROJECTION_RANK}"
echo "  normalization=${SPEL_PGD_DIRECTION_NORMALIZATION}, pgd_lr_scale=${SPEL_PGD_PGD_LR_SCALE}"
echo "  train_tokens=${TRAIN_TOKENS}, lr=${LR}, run_root=${RUN_ROOT}"

RUN_ROOT="$RUN_ROOT" \
WIDTH="$WIDTH" \
NUM_LAYERS="$NUM_LAYERS" \
SEQ_LENGTH="$SEQ_LENGTH" \
HEAD_DIM="$HEAD_DIM" \
GLOBAL_BATCH="$GLOBAL_BATCH" \
MICRO_BATCH="$MICRO_BATCH" \
TRAIN_TOKENS="$TRAIN_TOKENS" \
LR="$LR" \
MIN_LR="$MIN_LR" \
LR_WARMUP_ITERS="$LR_WARMUP_ITERS" \
EVAL_INTERVAL="$EVAL_INTERVAL" \
EVAL_ITERS="$EVAL_ITERS" \
LOG_INTERVAL="$LOG_INTERVAL" \
CPUS_PER_TASK="$CPUS_PER_TASK" \
SPEL_PGD_BRANCH_MODE="$SPEL_PGD_BRANCH_MODE" \
SPEL_PGD_PROJECTION_MODE="$SPEL_PGD_PROJECTION_MODE" \
SPEL_PGD_PROJECTION_RANK="$SPEL_PGD_PROJECTION_RANK" \
SPEL_PGD_SIGMA2_POWER_ITERATION_STEPS="$SPEL_PGD_SIGMA2_POWER_ITERATION_STEPS" \
SPEL_PGD_GAP_ESTIMATOR_MODE="$SPEL_PGD_GAP_ESTIMATOR_MODE" \
SPEL_PGD_DIRECTION_NORMALIZATION="$SPEL_PGD_DIRECTION_NORMALIZATION" \
SPEL_PGD_PGD_LR_SCALE="$SPEL_PGD_PGD_LR_SCALE" \
SPEL_PGD_TANGENT_PROJECT_AFTER_MSIGN="$SPEL_PGD_TANGENT_PROJECT_AFTER_MSIGN" \
SPEL_PGD_GAP_THRESHOLDS="$SPEL_PGD_GAP_THRESHOLDS" \
bash "$SUBMIT_SCRIPT"
